hub:
  cookieSecret: "faec6a40f903cfee503e1d68b3da94ea1c5489f0c1c8177e43ea27b8d243e637"
proxy:
  secretToken: "7fdacaa4b3a2eac69f94ed30ee8fd8aff06744379386d9b1d734856fa5404b43"
singleuser:
  image:
    name: henchc/dlab-workshops
    tag: latest
  memory:
      limit: 1G
      guarantee: 1G
  storage:
    capacity: 2Gi
    storageClass:
      parameters:
         type: pd-ssd
